//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------
#include "pch.h"

#if defined _DEBUG && !defined DISABLE_XAML_GENERATED_BINDING_DEBUG_OUTPUT
extern "C" __declspec(dllimport) int __stdcall IsDebuggerPresent();
#endif

#include "AlbumPage.xaml.h"

void ::App2::AlbumPage::InitializeComponent()
{
    if (_contentLoaded)
    {
        return;
    }
    _contentLoaded = true;
    ::Windows::Foundation::Uri^ resourceLocator = ref new ::Windows::Foundation::Uri(L"ms-appx:///AlbumPage.xaml");
    ::Windows::UI::Xaml::Application::LoadComponent(this, resourceLocator, ::Windows::UI::Xaml::Controls::Primitives::ComponentResourceLocation::Application);
}

void ::App2::AlbumPage::Connect(int __connectionId, ::Platform::Object^ __target)
{
    switch (__connectionId)
    {
        case 1:
            {
                this->AlbumGrid = safe_cast<::Windows::UI::Xaml::Controls::GridView^>(__target);
            }
            break;
        case 2:
            {
                this->ToUserProfile = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->ToUserProfile))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::App2::AlbumPage::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&AlbumPage::ToUserProfile_Click_1);
            }
            break;
        case 3:
            {
                this->AlbumButton = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->AlbumButton))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::App2::AlbumPage::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&AlbumPage::AlbumButton_Click_1);
            }
            break;
    }
    _contentLoaded = true;
}

::Windows::UI::Xaml::Markup::IComponentConnector^ ::App2::AlbumPage::GetBindingConnector(int __connectionId, ::Platform::Object^ __target)
{
    __connectionId;         // unreferenced
    __target;               // unreferenced
    return nullptr;
}


