#pragma once
//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------


namespace Windows {
    namespace UI {
        namespace Xaml {
            namespace Controls {
                ref class Button;
                ref class TextBlock;
                ref class TextBox;
            }
        }
    }
}

namespace App2
{
    [::Windows::Foundation::Metadata::WebHostHidden]
    partial ref class PostToFeedPage : public ::Windows::UI::Xaml::Controls::Page, 
        public ::Windows::UI::Xaml::Markup::IComponentConnector,
        public ::Windows::UI::Xaml::Markup::IComponentConnector2
    {
    public:
        void InitializeComponent();
        virtual void Connect(int connectionId, ::Platform::Object^ target);
        virtual ::Windows::UI::Xaml::Markup::IComponentConnector^ GetBindingConnector(int connectionId, ::Platform::Object^ target);
    
    private:
        bool _contentLoaded;
    
        private: ::Windows::UI::Xaml::Controls::Button^ toUserProfile;
        private: ::Windows::UI::Xaml::Controls::Button^ Post;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ mainPostLabel;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ linkLabel;
        private: ::Windows::UI::Xaml::Controls::TextBox^ link;
    };
}

