#pragma once
//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------


namespace Windows {
    namespace UI {
        namespace Xaml {
            namespace Controls {
                ref class Button;
                ref class TextBlock;
            }
        }
    }
}
namespace winsdkfb {
    ref class ProfilePictureControl;
}

namespace App2
{
    [::Windows::Foundation::Metadata::WebHostHidden]
    partial ref class UserProfile : public ::Windows::UI::Xaml::Controls::Page, 
        public ::Windows::UI::Xaml::Markup::IComponentConnector,
        public ::Windows::UI::Xaml::Markup::IComponentConnector2
    {
    public:
        void InitializeComponent();
        virtual void Connect(int connectionId, ::Platform::Object^ target);
        virtual ::Windows::UI::Xaml::Markup::IComponentConnector^ GetBindingConnector(int connectionId, ::Platform::Object^ target);
    
    private:
        bool _contentLoaded;
    
        private: ::Windows::UI::Xaml::Controls::Button^ logoutButton;
        private: ::Windows::UI::Xaml::Controls::Button^ sendMessageButton;
        private: ::Windows::UI::Xaml::Controls::Button^ PostToFeedButton;
        private: ::Windows::UI::Xaml::Controls::Button^ albumsButton;
        private: ::winsdkfb::ProfilePictureControl^ ProfilePic;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ userName;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ surName;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ gender;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ email;
    };
}

