//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------
#include "pch.h"

#if defined _DEBUG && !defined DISABLE_XAML_GENERATED_BINDING_DEBUG_OUTPUT
extern "C" __declspec(dllimport) int __stdcall IsDebuggerPresent();
#endif

#include "UserProfile.xaml.h"

void ::App2::UserProfile::InitializeComponent()
{
    if (_contentLoaded)
    {
        return;
    }
    _contentLoaded = true;
    ::Windows::Foundation::Uri^ resourceLocator = ref new ::Windows::Foundation::Uri(L"ms-appx:///UserProfile.xaml");
    ::Windows::UI::Xaml::Application::LoadComponent(this, resourceLocator, ::Windows::UI::Xaml::Controls::Primitives::ComponentResourceLocation::Application);
}

void ::App2::UserProfile::Connect(int __connectionId, ::Platform::Object^ __target)
{
    switch (__connectionId)
    {
        case 1:
            {
                this->logoutButton = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->logoutButton))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::App2::UserProfile::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&UserProfile::logoutClick);
            }
            break;
        case 2:
            {
                this->sendMessageButton = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->sendMessageButton))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::App2::UserProfile::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&UserProfile::sendMessageButtonClick);
            }
            break;
        case 3:
            {
                this->PostToFeedButton = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->PostToFeedButton))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::App2::UserProfile::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&UserProfile::PostToFeedButtonClick);
            }
            break;
        case 4:
            {
                this->albumsButton = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->albumsButton))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::App2::UserProfile::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&UserProfile::albumsClick);
            }
            break;
        case 5:
            {
                this->ProfilePic = safe_cast<::winsdkfb::ProfilePictureControl^>(__target);
            }
            break;
        case 6:
            {
                this->userName = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(__target);
            }
            break;
        case 7:
            {
                this->surName = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(__target);
            }
            break;
        case 8:
            {
                this->gender = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(__target);
            }
            break;
        case 9:
            {
                this->email = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(__target);
            }
            break;
    }
    _contentLoaded = true;
}

::Windows::UI::Xaml::Markup::IComponentConnector^ ::App2::UserProfile::GetBindingConnector(int __connectionId, ::Platform::Object^ __target)
{
    __connectionId;         // unreferenced
    __target;               // unreferenced
    return nullptr;
}


